### ISSUE TITLE
Changes to readme

### ISSUE THREAD

**Issue by jolidog** [marzeelabs/mz-harp#6]
to run harp init you need harp as a cli already available, so under the setup section, point 4 should be point 1.
1. Install gulp and harp globally with npm install -g gulp harp so you get the CLIs available
2. Setup boilerplate: harp init my-harp --boilerplate marzeelabs/mz-harp
3. Navigate inside the new directory with cd my-harp
4. Install all dependencies with npm install

**Comment by pvhee** [comment]
@jolidog PRs welcome!

**Comment by pvhee** [comment]
Updated and fixed in https://github.com/marzeelabs/generator-mzharp/blob/master/generators/app/templates/README.md

**Comment by pvhee** [comment]
@jolidog ^^
